spring:
  application:
    name: gymMagicAdministrator
  datasource:
    url: jdbc:postgresql://localhost:5432/GymMagic
    username: postgres
    password: '81942686'
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 9010

management:
  security:
    enabled: false




